import Head from "next/head";
import Image from "next/image";
import Link from "next/Link";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 22px;
          }
        `}
      </style>
      <Head>
        <title>Curious Coder</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
     
      <main className={styles.main}>
        <h1 className={styles.title}>Curious Coder</h1>
        <Image
          src="/pics.jpg"
          className={styles.Myimg}
          width={300}
          height={150}
        />
        <p>A blog by a coder for all the coders round the world</p>
        <span className={styles.MyPersonalBlogHeading}>Personal Blog List</span>
        <div className="blogItem">
          <h3>How to learn Java?</h3>
          <p>Java is the language used to design logic on the web.</p>
        </div>
        <div className="blogItem">
          <h3>How to learn Python?</h3>
          <p>Java is the language used to design logic on the web.</p>
        </div>
        <div className="blogItem">
          <h3>How to learn C++?</h3>
          <p>Java is the language used to design logic on the web.</p>
        </div>
        <div className="blogItem">
          <h3>How to learn JavaScript?</h3>
          <p>Java is the language used to design logic on the web.</p>
        </div>
      </main>
    </div>
  );
}
