import Head from "next/head";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 22px;
          }
        `}
      </style>
      <Head>
        <title> Curious Coder </title>{" "}
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}> Curious Coder </h1>{" "}
        
        <img className={styles.Myimg} src="pics.jpg" width={300} height={150} alt="Curious Coder"/>
        <p className={styles.frontLine}> A blog by a coder for all the coders round the world. </p>{" "}
        <span className={styles.MyPersonalBlogHeading}>
          Personal Blog List
        </span>
        <div className="blogItem">
          <h3 className={styles.blogh}> How to learn Java ? </h3>
          <p className={styles.bloghp}>This blog will teach you how to run programs using Java Programming Language.</p>
        </div>
        <div className="blogItem">
          <h3 className={styles.blogh}> How to learn Python ? </h3>
          <p className={styles.bloghp}> This blog will teach you how to run programs using Java Programming Language. </p>
        </div>
        <div className="blogItem">
          <h3 className={styles.blogh}> How to learn C++ ? </h3>
          <p className={styles.bloghp}> This blog will teach you how to run programs using Java Programming Language. </p>
        </div>
        <div className="blogItem">
          <h3 className={styles.blogh}> How to learn JavaScript ? </h3>
          <p className={styles.bloghp}>This blog will teach you how to run programs using Java Programming Language. </p>
        </div>
      </main>
      <footer className={styles.footer}>
  <span>Copyrights Reserved </span>
 &nbsp;
  <span>&copy;2022</span>
</footer>
    </div>
   
  );
}
